SET 'auto.offset.reset' = 'earliest';

CREATE STREAM TEMPERATURE_CSV (
  CITY STRING,
  MEASURE_DATE STRING,
  TEMPERATURE DOUBLE
) WITH (
  KAFKA_TOPIC = 'TEMPERATURE_RAW',
  KEY_FORMAT = 'KAFKA',
  PARTITIONS = 1,
  VALUE_FORMAT = 'DELIMITED',
  VALUE_DELIMITER = ';',
  TIMESTAMP = 'MEASURE_DATE',
  TIMESTAMP_FORMAT = 'yyyy-MM-dd HH:mm:ss.SSS'
);

CREATE STREAM TEMPERATURE_YEAR
WITH (
  VALUE_FORMAT = 'JSON_SR'
)
AS SELECT CITY, SUBSTRING(MEASURE_DATE, 1, 4) AS YEAR, TEMPERATURE FROM TEMPERATURE_CSV;

CREATE TABLE TEMPERATURE_AVERAGE
WITH (
  KEY_FORMAT = 'JSON_SR',
  VALUE_FORMAT = 'JSON_SR'
)
AS SELECT CITY, YEAR, ROUND(AVG(TEMPERATURE), 2) AS TEMPERATURE FROM TEMPERATURE_YEAR
GROUP BY CITY, YEAR;
